apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: api-namespace
spec:
  selector:
    app: mongodb
  ports:
    - port: {{ .Values.mongodb.port}}
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: api-namespace
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
---
kind: Service
apiVersion: v1
metadata:
  name: api-service
  namespace: api-namespace
spec:
  selector:
    app: apiapp
  ports:
    - port: 80 
      targetPort: {{ .Values.apiapp.containerPort}}
      protocol: TCP
  type: NodePort