name: Build and Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - main  # Trigger on push to the main branch

env:
  AWS_REGION: us-east-1
  ECR_REPO: sre_ecr_repo
  CLUSTER_NAME: api-cluster-1
  NAMESPACE: api-namespace
  HELM_RELEASE: sreapi

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/arm64 -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}:latest .
        docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}:latest

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

    - name: Deploy with Helm
      run: |
        AWS_ACCOUNT_ID=$(echo ${{ steps.login-ecr.outputs.registry }} | cut -d'.' -f1)
        helm upgrade --install $HELM_RELEASE sreapi/ \
          --namespace $NAMESPACE \
          --create-namespace \
          --atomic \
          --set awsAccountId=$AWS_ACCOUNT_ID